spring.application.name=fin-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/fintracker
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true